copy __.txt C:\moon\dev\github\hopelife\moonRepo\_doing\book\ETC\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_doing\book\HB\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_doing\book\IT\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_doing\book\KM\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_doing\down\ETC\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_doing\down\HB\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_doing\down\IT\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_doing\down\KM\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_doing\mine\book\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_doing\mine\essay\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_doing\mine\novel\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_doing\mine\paper\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_doing\mine\poem\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_doing\mine\work\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_doing\mine\_etc\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_doing\temp\ETC\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_doing\temp\HB\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_doing\temp\IT\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_doing\temp\KM\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\book\ETC\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\book\HB\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\book\IT\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\book\KM\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\down\ETC\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\down\HB\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\down\IT\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\down\KM\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\mine\book\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\mine\essay\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\mine\novel\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\mine\paper\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\mine\poem\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\mine\work\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\mine\_etc\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\temp\ETC\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\temp\HB\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\temp\IT\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\temp\KM\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_doc\book\ETC\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_doc\book\HB\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_doc\book\IT\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_doc\book\KM\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_doc\down\ETC\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_doc\down\HB\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_doc\down\IT\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_doc\down\KM\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_doc\mine\book\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_doc\mine\essay\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_doc\mine\novel\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_doc\mine\paper\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_doc\mine\poem\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_doc\mine\work\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_doc\mine\_etc\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_doc\temp\ETC\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_doc\temp\HB\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_doc\temp\IT\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_doc\temp\KM\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_ebook\book\ETC\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_ebook\book\HB\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_ebook\book\IT\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_ebook\book\KM\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_ebook\down\ETC\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_ebook\down\HB\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_ebook\down\IT\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_ebook\down\KM\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_ebook\mine\book\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_ebook\mine\essay\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_ebook\mine\novel\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_ebook\mine\paper\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_ebook\mine\poem\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_ebook\mine\work\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_ebook\mine\_etc\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_ebook\temp\ETC\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_ebook\temp\HB\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_ebook\temp\IT\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_ebook\temp\KM\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_hwp\book\ETC\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_hwp\book\HB\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_hwp\book\IT\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_hwp\book\KM\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_hwp\down\ETC\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_hwp\down\HB\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_hwp\down\IT\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_hwp\down\KM\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_hwp\mine\book\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_hwp\mine\essay\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_hwp\mine\novel\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_hwp\mine\paper\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_hwp\mine\poem\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_hwp\mine\work\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_hwp\mine\_etc\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_hwp\temp\ETC\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_hwp\temp\HB\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_hwp\temp\IT\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_hwp\temp\KM\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_markdown\book\ETC\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_markdown\book\HB\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_markdown\book\IT\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_markdown\book\KM\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_markdown\down\ETC\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_markdown\down\HB\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_markdown\down\IT\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_markdown\down\KM\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_markdown\mine\book\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_markdown\mine\essay\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_markdown\mine\novel\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_markdown\mine\paper\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_markdown\mine\poem\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_markdown\mine\work\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_markdown\mine\_etc\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_markdown\temp\ETC\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_markdown\temp\HB\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_markdown\temp\IT\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_markdown\temp\KM\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_pdf\book\ETC\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_pdf\book\HB\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_pdf\book\IT\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_pdf\book\KM\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_pdf\down\ETC\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_pdf\down\HB\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_pdf\down\IT\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_pdf\down\KM\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_pdf\mine\book\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_pdf\mine\essay\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_pdf\mine\novel\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_pdf\mine\paper\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_pdf\mine\poem\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_pdf\mine\work\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_pdf\mine\_etc\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_pdf\temp\ETC\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_pdf\temp\HB\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_pdf\temp\IT\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_pdf\temp\KM\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_ppt\book\ETC\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_ppt\book\HB\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_ppt\book\IT\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_ppt\book\KM\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_ppt\down\ETC\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_ppt\down\HB\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_ppt\down\IT\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_ppt\down\KM\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_ppt\mine\book\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_ppt\mine\essay\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_ppt\mine\novel\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_ppt\mine\paper\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_ppt\mine\poem\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_ppt\mine\work\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_ppt\mine\_etc\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_ppt\temp\ETC\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_ppt\temp\HB\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_ppt\temp\IT\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_ppt\temp\KM\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_xls\book\ETC\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_xls\book\HB\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_xls\book\IT\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_xls\book\KM\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_xls\down\ETC\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_xls\down\HB\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_xls\down\IT\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_xls\down\KM\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_xls\mine\book\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_xls\mine\essay\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_xls\mine\novel\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_xls\mine\paper\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_xls\mine\poem\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_xls\mine\work\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_xls\mine\_etc\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_xls\temp\ETC\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_xls\temp\HB\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_xls\temp\IT\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_done\_xls\temp\KM\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_draft\book\ETC\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_draft\book\HB\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_draft\book\IT\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_draft\book\KM\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_draft\down\ETC\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_draft\down\HB\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_draft\down\IT\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_draft\down\KM\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_draft\mine\book\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_draft\mine\essay\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_draft\mine\novel\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_draft\mine\paper\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_draft\mine\poem\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_draft\mine\work\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_draft\temp\ETC\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_draft\temp\HB\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_draft\temp\IT\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_draft\temp\KM\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_meta\guide\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_meta\note\__.txt
copy __.txt C:\moon\dev\github\hopelife\moonRepo\_meta\plan\__.txt
copy __.txt \__.txt